name: dbus-app-launcher
version: 0.1.0.0

synopsis: "Simple app launcher for D-Bus"
description: "See the README at <https://github.com/DvdGiessen/dbus-app-launcher>"
category: System

author: Daniël van de Giessen
maintainer: daniel@dvdgiessen.nl
github: DvdGiessen/dbus-app-launcher
copyright: "2024 Daniël van de Giessen"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  dbus-app-launcher:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - containers
      - dbus
      - extra
      - unix

