name: dbus-app-launcher
version: 0.1.0.0

synopsis: "Simple app launcher for D-Bus"
description: "See the README at <https://github.com/DvdGiessen/dbus-app-launcher>"
category: System

author: Daniël van de Giessen
maintainer: daniel@dvdgiessen.nl
github: DvdGiessen/dbus-app-launcher
copyright: "2024 Daniël van de Giessen"

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.12 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  dbus-app-launcher:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - containers >= 0.6
      - dbus >= 1.3
      - extra >= 1.7
      - regex-tdfa >= 1.3
      - shellwords >= 0.1.3.2
      - unix >= 2.8
